name: Build ghostty for Debian

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Ghostty release tag'
        required: true
        default: 'v1.2.3'

jobs:
  build-deb:
    strategy:
      matrix:
        include:
          - arch: arm64
            builder: ubuntu-24.04-arm
          - arch: x86
            builder: ubuntu-latest

    name: Build
    runs-on: ${{ matrix.builder }}

    container:
      image: debian:sid


    env:
      VERSION: ${{ github.event.inputs.version }}
      ARCH: ${{ matrix.arch }}

    steps:
      - name: Install build dependencies
        run: |
          apt-get update

          apt-get install -y \
            xz-utils \
            tar \
            curl \
            build-essential \
            pkg-config \
            gettext \
            blueprint-compiler \
            pandoc \
            bzip2 \
            libxml2-utils \
            libonig-dev \
            libgtk4-layer-shell-dev \
            libgtk4-layer-shell0 \
            libfreetype6-dev \
            libgtk-4-dev \
            libadwaita-1-dev \
            libglib2.0-dev \
            libpango1.0-dev \
            libcairo2-dev \
            libgdk-pixbuf-2.0-dev

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.14.0

      - name: Checkout ghostty
        uses: actions/checkout@v4
        with:
          repository: ghostty-org/ghostty
          ref: ${{ env.VERSION }}
          fetch-depth: 1

      # needed till https://github.com/ghostty-org/ghostty/issues/9606
      - name: Patch iterm2 themes URL and hash
        run: |
          sed -i 's|https://github.com/mbadolato/iTerm2-Color-Schemes.*|https://deps.files.ghostty.org/ghostty-themes-release-20260202-151632-49169e9.tgz",|' build.zig.zon
          sed -i 's|N-V-__8AALIsAwDyo88G5mGJGN2lSVmmFMx4YePfUvp_2o3Y|N-V-__8AAKlTAwClvdUfsAoiLgM6sb2NPZNnS6wzCiIs252Z|' build.zig.zon
          sed -i 's|https://github.com/mbadolato/iTerm2-Color-Schemes.*|https://deps.files.ghostty.org/ghostty-themes-release-20260202-151632-49169e9.tgz|' build.zig.zon.txt

      - name: Prepare
        run: |
          ZIG_GLOBAL_CACHE_DIR=/tmp/offline-cache ./nix/build-support/fetch-zig-cache.sh

      - name: Build ghostty
        run: |
          DESTDIR=debian/pkg zig build \
            --prefix "/usr" \
            --system /tmp/offline-cache/p \
            -Doptimize=ReleaseFast \
            -Dcpu=baseline


      - name: Prepare Debian package structure
        run: |
          mkdir -p debian/pkg/DEBIAN

          cat <<EOF > debian/pkg/DEBIAN/control
          Package: ghostty
          Version: ${VERSION#v}
          Depends: libgtk4-layer-shell0 libadwaita-1-0
          Priority: optional
          Architecture: ${ARCH}
          Maintainer: Your Name <you@example.com>
          Description: Ghostty is a fast, feature-rich, and cross-platform terminal emulator that uses platform-native UI and GPU acceleration.
          EOF

      - name: Build .deb package
        run: |
          fakeroot dpkg-deb --build debian/pkg ghostty_${VERSION#v}_${ARCH}.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ghostty-deb-${{ env.ARCH }}
          path: |
            ghostty*.deb
